[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "node server.cjs"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
sleepApplication = false

[[deploy.services]]
name = "web"
port = 8080

[deploy.multiRegionConfig]
[deploy.multiRegionConfig."us-west2"]
numReplicas = 1