name: CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run health check test
      run: |
        # Start server in background
        PORT=8080 node server.cjs &
        SERVER_PID=$!

        # Wait for server to start
        sleep 5

        # Test health endpoint
        curl -f http://localhost:8080/health || exit 1

        # Kill server
        kill $SERVER_PID

    - name: Check for vulnerabilities
      run: npm audit --audit-level=moderate
      continue-on-error: true

  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t mcp-platform:test .

    - name: Test Docker container
      run: |
        # Run container
        docker run -d -p 8080:8080 --name test-container mcp-platform:test

        # Wait for container to be ready
        sleep 10

        # Test health endpoint
        curl -f http://localhost:8080/health || exit 1

        # Stop and remove container
        docker stop test-container
        docker rm test-container

  railway-deploy:
    runs-on: ubuntu-latest
    needs: [test, docker-build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Railway
      run: echo "Railway auto-deploys from GitHub connection"

    - name: Notify deployment
      run: |
        echo "✅ Deployment triggered for commit ${{ github.sha }}"
        echo "📦 Railway will auto-deploy from master branch"